"""added image column to items

Revision ID: 28404bb226ae
Revises: c3631703572d
Create Date: 2024-06-19 23:45:31.025690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28404bb226ae'
down_revision = 'c3631703572d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('Image')

    # ### end Alembic commands ###
