"""changed tablenames to lowercase

Revision ID: a6bfec62a7d4
Revises: ec96084c4f58
Create Date: 2024-06-19 22:36:10.444153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a6bfec62a7d4'
down_revision = 'ec96084c4f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('ID', sa.String(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('Quantity', sa.Integer(), nullable=True),
    sa.Column('Price', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Items')
    op.drop_table('Users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Users_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Users_pkey')
    )
    op.create_table('Items',
    sa.Column('ID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Price', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ID', name='Items_pkey')
    )
    op.drop_table('users')
    op.drop_table('items')
    # ### end Alembic commands ###
