"""added Users and Items tables

Revision ID: ec96084c4f58
Revises: 
Create Date: 2024-06-19 22:16:29.011342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec96084c4f58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Items',
    sa.Column('ID', sa.String(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('Quantity', sa.Integer(), nullable=True),
    sa.Column('Price', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    op.drop_table('Items')
    # ### end Alembic commands ###
