"""empty message

Revision ID: 04213a9042de
Revises: 
Create Date: 2024-06-21 17:21:59.453219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04213a9042de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('ID', sa.String(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('Quantity', sa.Integer(), nullable=True),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('Price', sa.String(), nullable=True),
    sa.Column('Image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('items')
    # ### end Alembic commands ###
