"""added service table

Revision ID: f76b05993a84
Revises: 04213a9042de
Create Date: 2024-06-27 17:58:54.477711

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f76b05993a84'
down_revision = '04213a9042de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('ID', sa.String(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('Address', sa.String(), nullable=True),
    sa.Column('Service', sa.String(), nullable=True),
    sa.Column('Phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ID', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('Name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('Password', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('password')
        batch_op.drop_column('name')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('password', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.drop_column('Password')
        batch_op.drop_column('Name')
        batch_op.drop_column('ID')

    op.drop_table('service')
    # ### end Alembic commands ###
